@startuml Actores

left to right direction

actor Cliente
actor Tecnico

note right of Cliente
**Cliente**:
Inicia el ciclo mediante solicitudes
y recibe respuestas
end note

note right of Tecnico
**Tecnico**:
Se encarga de ver los formularios 
pendientes y resolverlos
end note

@enduml
