@startuml CompletarFormulario

skinparam linetype polyline

state completarFormulario as "completarFormulario()" {

state " " as AccediendoFormulario
state " " as RellenandoFormulario
state " " as RevisandoFormulario

[*] -[#green]-> AccediendoFormulario
note on link
<b>Cliente</b> accede al formulario
para aportar informacion adicional
end note

AccediendoFormulario -[#green]-> RellenandoFormulario
note on link
<b>Cliente</b> completa los campos
requeridos
end note

RellenandoFormulario -[#green]-> RevisandoFormulario
note on link
<b>Cliente</b> revisa la informacion
introducida
end note

RevisandoFormulario -[#green]-> [*]
note on link
<b>Cliente</b> esta conforme
y envia el formulario
end note

RevisandoFormulario -[#red]-> RellenandoFormulario
note on link
<b>Cliente</b> no esta conforme
y modifica la informacion
end note

}

completarFormulario -[#green]-> SISTEMA

completarFormulario -[#red]-> ERROR_FORMULARIO

@enduml
