@startuml VerSolicitudesPendientes

skinparam linetype polyline

state verSolicitudes as "verSolicitudesPendientes()" {

state " " as AccediendoVista
state " " as CargandoSolicitudes
state " " as VisualizandoSolicitudes

[*] -[#green]-> AccediendoVista
note on link
<b>Tecnico</b> accede a la vista
de solicitudes pendientes
end note

AccediendoVista -[#green]-> CargandoSolicitudes
note on link
<b>Sistema</b> consulta las solicitudes
pendientes
end note

CargandoSolicitudes -[#green]-> VisualizandoSolicitudes
note on link
<b>Sistema</b> muestra las solicitudes
al tecnico
end note

VisualizandoSolicitudes -[#green]-> [*]
note on link
<b>Tecnico</b> revisa la información
disponible
end note

}

verSolicitudes -[#green]-> VISTA_DATOS

verSolicitudes -[#red]-> ERROR_CARGA

@enduml
