@startuml ActualizarEstado
top to bottom direction

actor Tecnico

package "ActualizarEstado()" {

  rectangle "ActualizarEstadoView" as View
  rectangle "ActualizarEstadoController" as Controller
  rectangle "Solicitud" as Solicitud

  Controller -[hidden]-> Solicitud
  View -[hidden]right-> Solicitud

  View --> Controller : enviarActualizacion(id, estado)
  Controller --> Solicitud : modificarEstado(id, estado)

}

Tecnico --> View : actualizarEstado(id, estado)

@enduml