@startuml CompletarFormulario
top to bottom direction

actor Cliente

package "CompletarFormulario()" {

  rectangle "FormularioView" as View
  rectangle "CompletarFormularioController" as Controller
  rectangle "Formulario" as Formulario
  rectangle "Solicitud" as Solicitud

  Controller -[hidden]-> Formulario
  Formulario -[hidden]-> Solicitud
  View -[hidden]right-> Solicitud

  View --> Controller : enviarFormulario(datos)
  Controller --> Formulario : guardarFormulario(datos)
  Controller --> Solicitud : asociarFormulario()

}

Cliente --> View : completarFormulario(datos)

@enduml