@startuml EnviarSolicitud
top to bottom direction

actor Cliente

package "EnviarSolicitud()" {

  rectangle "EnvioSolicitudView" as View
  rectangle "EnviarSolicitudController" as Controller
  rectangle "Solicitud" as Solicitud

  Controller -[hidden]-> Solicitud
  View -[hidden]right-> Solicitud

  View --> Controller : procesarSolicitud(datos)
  Controller --> Solicitud : crearSolicitud(datos)
}

Cliente --> View : enviarSolicitud(datos)

@enduml