@startuml RecibirRespuesta
top to bottom direction

actor Cliente

package "RecibirRespuesta()" {

  rectangle "RespuestaSolicitudView" as View
  rectangle "RecibirRespuestaController" as Controller
  rectangle "Solicitud" as Solicitud
  rectangle "Respuesta" as Respuesta

  Controller -[hidden]-> Solicitud
  Solicitud -[hidden]-> Respuesta
  View -[hidden]right-> Respuesta

  View --> Controller : solicitarRespuesta()
  Controller --> Solicitud : obtenerSolicitud()
  Controller --> Respuesta : generarRespuesta()

}

Cliente --> View : recibirRespuesta()

@enduml