@startuml DdC_Cliente

top to bottom direction

package "Proyecto" {

rectangle Cliente
rectangle Sistema
rectangle Formulario

Cliente --> Sistema : Enviar solicitud
Sistema --> Cliente : Recibir respuesta
Cliente --> Formulario : Completar formulario

}

@enduml