@startuml CdU_PowerAutomate
left to right direction

actor PowerAutomate


package "Entrada" {
    usecase "Procesar correo entrante" as ProcesarCorreo
}

package "Procesamiento" {
    usecase "Registrar información" as RegistrarInformacion
    usecase "Procesar información" as ProcesarSolicitud
    usecase "Consultar información" as ConsultarInformacion
    usecase "Analizar solicitud" as AnalizarSolicitud
}

package "Salida" {
    usecase "Enviar respuesta al cliente" as EnviarRespuesta
    usecase "Generar respuesta" as GenerarRespuesta
}

PowerAutomate --> ProcesarCorreo
PowerAutomate --> ProcesarSolicitud
PowerAutomate --> AnalizarSolicitud
PowerAutomate --> ConsultarInformacion
PowerAutomate --> RegistrarInformacion
PowerAutomate --> GenerarRespuesta
PowerAutomate --> EnviarRespuesta

@enduml